export enum MutationKey {
  AddToCart = "add-to-cart",
  AddToComparisons = "add-to-comparisons",
  AddToWishlist = "add-to-wishlist",
  CartClear = "cart-clear",
  Checkout = "checkout",
  Credentials = "credentials",
  EditUser = "edit-user",
  LeaveReview = "leave-review",
  Login = "login",
  Logout = "logout",
  Profile = "profile",
  RequestResetPassword = "request-reset-password",
  ResetPassword = "reset-password",
}
